In [1]:
import torch
import numpy as np

### Tensor 初始化

Tensor 就是跟numpy的ndarray 很像，无论从底层内存的共享还是基础的操作上，两者有很多共同的地方。Tensor可以指定不同的硬件作为载体，同时在自动的微分方面有很多的自己独特的优势。

Tensor的初始化可以右很多左方式：
- 直接通过python列表
- Numpy array
- 利用其他的tensor
- 使用随机值或者常量值

In [4]:
# 直接通过python列表
data = [[1,2],[3,4]]
# 这个是官方推荐的写法,工厂函数,自动推断其参数的类型
x_data = torch.tensor(data)
# 这个是里所有构造函数来定义tensor，构造的张量使用全局默认值
# 所以其数据的类型使用全局默认的值torch.float32
X_data = torch.Tensor(data)

print(f"x_data: {x_data} : type: {x_data.dtype}")
print(f"X_data: {X_data} : type: {X_data.dtype}")

x_data: tensor([[1, 2],
        [3, 4]]) : type: torch.int64
X_data: tensor([[1., 2.],
        [3., 4.]]) : type: torch.float32


In [7]:
# 有numpy进行创建
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)
print(x_np.dtype)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
torch.int32


In [9]:
# 利用已有的tensor来构建
x_ones = torch.ones_like(x_data)
print(f"One Tensor:\n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor:\n {x_rand} \n")

One Tensor:
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor:
 tensor([[1.9787e-01, 3.8925e-01],
        [8.5138e-01, 2.8956e-04]]) 



In [24]:
# 利用shape来构建
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n ")
print(f"Zeros Tensor: \n {zeros_tensor}")

print(rand_tensor.device)


Random Tensor: 
 tensor([[0.2997, 0.9521, 0.6172],
        [0.5856, 0.7823, 0.3496]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 
 
Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
cpu


In [27]:
# Tensor的属性: 形状尺寸，数据类型，存储的硬件的位置
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Tensor的操作
主要的操作有：
- 变换
- 引用
- 切片
- 数学操作
- 线性代数
- 随机采样
- ...

In [28]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print(f"save tensor on: {tensor.device}")

save tensor on: cuda:0


In [3]:
tensor = torch.ones(4,4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [4]:
t1 = torch.cat([tensor,tensor,tensor],dim=0)
print(t1)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [9]:
# 矩阵的乘积
y1 = tensor @ tensor.T
print(y1)
y2 = tensor.matmul(tensor.T)
print(y2)

y3 = torch.rand_like(tensor)
torch.matmul(tensor,tensor.T,out=y3)
print(y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [10]:
# 点乘
z1 = tensor * tensor
print(z1)

z2 = tensor.mul(tensor)
print(z2)

z3 = torch.rand_like(tensor)
torch.mul(tensor,tensor,out=z3)
print(z3)


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [14]:
agg = tensor.sum()
# print(tensor.item())
print(agg)
# 将tensor 转换成python形式的数据格式，使用item
# 只能是单个元素的时候可以使用
agg_item = agg.item()
print(agg_item,type(agg_item))

tensor(12.)
12.0 <class 'float'>


In [15]:
# In-place operations 原地操作符
# 就是指不经过数据复制，而是直接在原来的数据上进行改变
# 一般是方法下面带上：_
# 可以节省内空间，

print(tensor,"\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


### Tensor 与 numpy数据的转换
在cpu上的Tensor跟numpy的数据变量是共享内存的，如果改变一个另外一个也会跟着改变

In [16]:
# tensor to numpy
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [18]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([3., 3., 3., 3., 3.])
n: [3. 3. 3. 3. 3.]


In [22]:
# numpy to tensor
n = np.ones(5)
t = torch.from_numpy(n)

np.add(n,1,out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
