In [2]:
import torch
import numpy as np

### Tensor 初始化

Tensor 就是跟numpy的ndarray 很像，无论从底层内存的共享还是基础的操作上，两者有很多共同的地方。Tensor可以指定不同的硬件作为载体，同时在自动的微分方面有很多的自己独特的优势。

Tensor的初始化可以右很多左方式：
- 直接通过python列表
- Numpy array
- 利用其他的tensor
- 使用随机值或者常量值

In [4]:
# 直接通过python列表
data = [[1,2],[3,4]]
# 这个是官方推荐的写法,工厂函数,自动推断其参数的类型
x_data = torch.tensor(data)
# 这个是里所有构造函数来定义tensor，构造的张量使用全局默认值
# 所以其数据的类型使用全局默认的值torch.float32
X_data = torch.Tensor(data)

print(f"x_data: {x_data} : type: {x_data.dtype}")
print(f"X_data: {X_data} : type: {X_data.dtype}")

x_data: tensor([[1, 2],
        [3, 4]]) : type: torch.int64
X_data: tensor([[1., 2.],
        [3., 4.]]) : type: torch.float32


In [7]:
# 有numpy进行创建
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)
print(x_np.dtype)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
torch.int32


In [9]:
# 利用已有的tensor来构建
x_ones = torch.ones_like(x_data)
print(f"One Tensor:\n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor:\n {x_rand} \n")

One Tensor:
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor:
 tensor([[1.9787e-01, 3.8925e-01],
        [8.5138e-01, 2.8956e-04]]) 



In [24]:
# 利用shape来构建
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n ")
print(f"Zeros Tensor: \n {zeros_tensor}")

print(rand_tensor.device)


Random Tensor: 
 tensor([[0.2997, 0.9521, 0.6172],
        [0.5856, 0.7823, 0.3496]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 
 
Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
cpu


In [27]:
# Tensor的属性: 形状尺寸，数据类型，存储的硬件的位置
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Tensor的操作
主要的操作有：
- 变换
- 引用
- 切片
- 数学操作
- 线性代数
- 随机采样
- ...

In [28]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print(f"save tensor on: {tensor.device}")

save tensor on: cuda:0


In [29]:
tensor = torch.ones(4,4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [30]:
t1 = torch.cat([tensor,tensor,tensor],dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
