In [1]:
import torch
import torch.nn

In [34]:
x = torch.ones(5)
y = torch.zeros(3)
# 使用参数 requires_grad 表示需要进行梯度计算
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
#设置tensor的计算梯度的属性
# b.requires_grad_(False)
z = torch.matmul(x, w)+b

# 使用 functional来构造一个计算图
loss = torch.nn.functional.binary_cross_entropy_with_logits(z,y)

print(x,y,w,b,loss)

tensor([1., 1., 1., 1., 1.]) tensor([0., 0., 0.]) tensor([[ 2.1351e+00,  1.0517e+00,  2.9906e-01],
        [-1.1009e-01,  1.9343e+00, -4.0283e-04],
        [ 3.7336e-01,  1.0435e-01, -5.4106e-02],
        [ 3.8330e-01, -3.1716e-02, -1.2490e+00],
        [-9.3099e-02,  1.1238e+00, -4.2071e-01]], requires_grad=True) tensor([-0.1416,  0.7868,  0.2001], requires_grad=True) tensor(2.6187, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


In [30]:
print('Gradient function for z = ', z.grad_fn)
print('Gradient function for loss = ', loss.grad_fn)

Gradient function for z =  <AddBackward0 object at 0x0000018CEB71D0D0>
Gradient function for loss =  <BinaryCrossEntropyWithLogitsBackward0 object at 0x0000018CEB6C9580>


In [45]:
#计算梯度值
# 由于考虑到性能的原因，这里智能执行一次，因为只有一张计算图
# retain_graph = True 通过设置该参数，可以被反复调用
loss.backward(retain_graph = True)
print(w.grad)
print(b.grad)

tensor([[3.4004, 3.6414, 0.8325],
        [3.4004, 3.6414, 0.8325],
        [3.4004, 3.6414, 0.8325],
        [3.4004, 3.6414, 0.8325],
        [3.4004, 3.6414, 0.8325]])
tensor([3.4004, 3.6414, 0.8325])


#### 不需要计算梯度反向传播
- 将网络的一些参数frozen, 不需要进行修改的时候
- 加速计算，比如只用于推理，而不是训练的时候

In [46]:
z = torch.matmul(x, w) + b
print(z.requires_grad)

# 不追踪梯度
with torch.no_grad():
    z = torch.matmul(x, w) + b
print(z.requires_grad)

True
False


In [27]:
# 使用 detach 也快可以不追踪计算相关的梯度值
z = torch.matmul(x,w) + b
z_det = z.detach()
print(z_det.requires_grad)

False


In [ ]:
inp = torch.eye(5, requires_grad=True)
out = (inp+1).pow(2)

