In [1]:
import torch
import numpy as np

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [28]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor:\n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype=float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor:
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3129, 0.7434],
        [0.1754, 0.9658]], dtype=torch.float64) 



In [24]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape, dtype=int)
zeros_tensor = torch.zeros(shape, dtype=int)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.3495, 0.7730, 0.8960],
        [0.5388, 0.8335, 0.8287]]) 

Ones Tensor: 
 tensor([[1, 1, 1],
        [1, 1, 1]]) 

Zeros Tensor: 
 tensor([[0, 0, 0],
        [0, 0, 0]]) 



In [30]:
tensor = torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [32]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [57]:
tensor = torch.ones((4, 4))
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[1,:] = 2
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [55]:
t1 = torch.cat([tensor, tensor, tensor], dim=0)
print(t1)

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])


In [61]:
y1 = tensor @ tensor.T
#print(y2)
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)

torch.matmul(tensor, tensor.T, out=y3)
print(y3)

tensor([[ 4.,  8.,  4.,  4.],
        [ 8., 16.,  8.,  8.],
        [ 4.,  8.,  4.,  4.],
        [ 4.,  8.,  4.,  4.]])


In [63]:
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 1., 1., 1.],
        [4., 4., 4., 4.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [64]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

20.0 <class 'float'>


In [66]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [67]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [68]:
n = np.ones(5)
t = torch.from_numpy(n)
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [69]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
